import{s as l,i as a}from"./assets/vendor-1d1bb5a2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const d="45524929-4d44ab8f504de5084895de9cf",u="https://pixabay.com/api/";function p(n){const t=`${u}?key=${d}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(t).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}).then(s=>s.hits).catch(s=>{console.log("Error:",s)})}function f(n){const t=document.querySelector(".gallery");t.innerHTML="",n.forEach(o=>{const e=`
        <a href = "${o.largeImageURL}" class = "image-card">
        <img src = "${o.webformatURL}" alt = "${o.tags}" />
        <div class = "info">
        <p> <span class = "text-span">Likes</span> ${o.likes}</p>
        <p> <span class = "text-span">Views</span> ${o.views}</p>
        <p> <span class = "text-span">Comments</span> ${o.comments}</p>
        <p> <span class = "text-span">Downloads</span> ${o.downloads}</p>
        </div>
        </a>`;t.insertAdjacentHTML("beforeend",e)}),new l(".gallery a").refresh()}const h=document.querySelector(".input-text"),m=document.querySelector(".button-search"),c=document.querySelector(".loader");m.addEventListener("click",()=>{const n=h.value.trim();if(n===""){a.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}c.classList.remove("is-hidden"),p(n).then(t=>{c.classList.add("is-hidden"),t.length===0?a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):f(t)}).catch(t=>{c.classList.add("is-hidden"),a.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.log("Error fetching img:",t)})});
//# sourceMappingURL=commonHelpers.js.map
