import{s as d,i as a}from"./assets/vendor-5c957d73.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const u="45524929-4d44ab8f504de5084895de9cf",p="https://pixabay.com/api/";function f(o){const r=`${p}?key=${u}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(r).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>e.hits).catch(e=>{console.log("Error fetching images:",e)})}function l(o){const r=document.querySelector(".gallery");r.innerHTML="",o.forEach(e=>{const n=`
            <li class="image-card">
                <a href="${e.largeImageURL}">
                    <img src="${e.webformatURL}" alt="${e.tags}" />
                    <div class="info">
                        <p><span class="text-span">Likes</span> ${e.likes}</p>
                        <p><span class="text-span">Views</span> ${e.views}</p>
                        <p><span class="text-span">Comments</span> ${e.comments}</p>
                        <p><span class="text-span">Downloads</span> ${e.downloads}</p>
                    </div>
                </a>
            </li>`;r.insertAdjacentHTML("beforeend",n)})}const h=document.querySelector(".input-text"),c=document.querySelector(".loader"),m=document.querySelector(".search-form");let g=new d(".gallery a");m.addEventListener("submit",o=>{o.preventDefault();const r=h.value.trim();if(r===""){a.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}c.classList.remove("is-hidden"),f(r).then(e=>{c.classList.add("is-hidden"),e.length===0?(l([]),a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})):(l(e),g.refresh())}).catch(e=>{c.classList.add("is-hidden"),a.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.log("Error fetching img:",e)})});
//# sourceMappingURL=commonHelpers.js.map
